'''
Contains classes for electric field reconstruction
from Stark-split Rydberg EIT spectra 

Author: Mykhailo Vorobiov
'''
#%%
from typing import Callable, Dict
from numpy.typing import NDArray

import numpy as np
import matplotlib.pyplot as plt

import pandas as pd

from lmfit import minimize, Parameters, fit_report

from pinqued_tools.spectroscopy.spectrum import SpectralData, Axes0D
from pinqued_tools.spectroscopy.lineshapes import HoltsmarkLine
from pinqued_tools.spectroscopy.field_reference import FieldReference

class SignalSimulator():
    '''
    Class that based on the Rydberg levels Stark splitting 
    from generated by the `FieldReference` class simulates EIT spectra.
    '''
    def __init__(self, 
                 reference: FieldReference,
                 lineshape_func: Callable|None = None
                 ):
        self._reference = reference
        self._lineshape_func = lineshape_func

        if lineshape_func is None:
            print('No lineshape function provided, using Holtsmark lineshape by default.')
            self._hline_list = self._holtsmark_spectrum_prepare()
            print(len(self._hline_list))

    def _holtsmark_spectrum_prepare(self) -> list[HoltsmarkLine]:
        '''
        Simulate EIT signal for a given electric field using the Holtsmark lineshape.
        '''
        line_keys = self._reference.level_labels
        efield_reference = self._reference.efield
        stark_reference = self._reference.detunings[line_keys[0]]
        
        hline_list = []
        for key in line_keys:
             print(f'Preparing Holtsmark line for {key}...')
             stark_reference = self._reference.detunings[key]
             hline = HoltsmarkLine(efield_reference, stark_reference)
             # 1. Define your 4D parameter space
             freq_grid = np.linspace(-1200, 400, 300)  # <-- The frequency axis for the LUT
             efield_grid = np.linspace(0.0, 45.0, 30)
             E0_grid = np.linspace(0.01, 20.0, 20)
             width_grid = np.linspace(20.0, 50.0, 10)  # <-- The new dimension
             hline.build_lut(freq_grid, efield_grid, E0_grid, width_grid, base_model='2d')
             hline_list.append(hline)
             print(f'Finished preparing Holtsmark line for {key}.')

        print(f'Ready to simulate spectra with Holtsmark spectrum! Number of lines {len(hline_list)}')
        return hline_list

    def holtsmark_spectrum(self, 
                           freq: NDArray, 
                           params: Parameters
                           ) -> NDArray:
        '''
        Simulate EIT signal for a given electric field using the Holtsmark lineshape.
        '''
        efield = params['efield'].value
        scale_factor = params['amp'].value
        width = params['width'].value
        E0 = params['E0'].value
        r_amp = [params[f'rel_amp_{i}'].value for i in range(len(self._hline_list))]
        spectrum = np.zeros_like(freq)
        for hline, ai in zip(self._hline_list, r_amp):
            spectrum += hline(freq, efield, width, E0, ai)
        spectrum *= scale_factor
        return spectrum

    def holtsmark_spectrum_bg(self, 
                           freq: NDArray, 
                           params: Parameters
                           ) -> NDArray:
        '''
        Simulate EIT signal for a given electric field using the Holtsmark lineshape.
        '''
        signal = self.holtsmark_spectrum(freq, params)
        bg = self.bg_drifts(freq, params, poly_terms=2)
        spectrum = signal + bg
        return spectrum

    def signal(self, 
               freq: NDArray, 
               params: Parameters,
               **kwargs) -> NDArray[np.float64]:
        '''
        Simulate EIT signal for a given electric field
        '''
        scale_factor = params['amp'].value
        width_0 = params['width_0'].value
        gradE_dr = params['gradE_dr'].value
        efield = params['efield'].value

        ref = self._reference.interp(efield)

        spectrum = np.zeros_like(freq)
        r_amp = [params[f'rel_amp_{i}'].value for i in range(len(ref))]
        for (fpos, df_de), amp in zip(ref, r_amp):
            width = width_0  - df_de * gradE_dr
            spectrum += amp * self._lineshape_func(freq, fpos, width, **kwargs)
        spectrum *= scale_factor
        return spectrum
    
    def bg_drifts(self, 
                  freq: NDArray, 
                  params: Parameters,
                  poly_terms: int = 2,
                  **kwargs):
        coefs = [params[f'b{i}'].value for i in range(poly_terms) if params[f'b{i}'] is not None]
        poly = np.poly1d(coefs)
        if len(coefs) < poly_terms:
            return np.zeros_like(freq)
        return poly(freq)

    def signal_with_bg(self, 
                       freq: NDArray, 
                       params: Parameters,
                       poly_terms: int = 3,
                       **kwargs) -> NDArray[np.float64]:
        signal = self.signal(freq, params, **kwargs)
        bg = self.bg_drifts(freq, params, poly_terms=poly_terms)
        return signal + bg

    def signal_with_bg_shifted(self, 
                       freq: NDArray, 
                       params: Parameters,
                       poly_terms: int = 3,
                       **kwargs) -> NDArray[np.float64]:
        f_shifted = freq - params['f_shift'].value
        signal = self.signal(f_shifted, params, **kwargs)
        bg = self.bg_drifts(f_shifted, params, poly_terms=poly_terms)
        return signal + bg

#%%
if __name__=='__main__':
    # ----------------- Usage example ----------------------
    from pinqued_tools.spectroscopy.lineshapes import holtsmarkian
    from pinqued_tools.analysis.plotting import set_mpl_style
    set_mpl_style()

    # Read reference Rydberg splittings
    ref_path = 'G:\\My Drive\\Vaults\\WnM-AMO\\__Scripts\\calculated_stark_maps\\stark_map_25D_MHz.csv'
    ref = FieldReference(ref_path)

    # define parameters of the spectrum
    params = {'efield': 0.6,
              'amp': 150, 
              'width_0': 30, 
              'gradE_dr': 2,
              'rel_amp': [0.6, 0.6, 1.0, 1.0, 1.0],
              'b0': 1e-3, 'b1': 1e-2, 'b3': 1e-4}
    
    params_sim = Parameters()
    for key, value in params.items():
        if key == 'rel_amp':
            continue
        params_sim.add(key, value=value)
    
    params_lmfit = Parameters()
    params_lmfit.add('efield', value=params['efield'], min=-0.1)
    params_lmfit.add('amp', value=params['amp']-20.0)
    params_lmfit.add('width_0', value=params['width_0']+10.0)
    params_lmfit.add('gradE_dr', value=params['gradE_dr']-1.0)


    # Instantiate signal simulator object
    sim = SignalSimulator(ref, holtsmarkian)


    # Generate detunings
    freq = np.linspace(200, -1500, 700)

    # Simulate signal
    signal = sim.signal(freq, params=params_sim, normalized=True)

    sigma = 1.0
    noise = np.random.normal(loc=0, scale=sigma, size=signal.shape)/(signal+1)
    signal_err =  sigma/(signal+1)
    signal_noise = signal + noise

    spectrum = SpectralData(signal=signal_noise, 
                            axes = Axes0D(f=freq),
                            signal_err=signal_err)

    fm = FitModel(sim)
    df = DataFitter(spectrum, fm).fit(params_lmfit)
    print(fit_report(df))
    print(df.params)

    # Plot results
    fig, ax = plt.subplots(figsize=(4,2))
    ax.set_title(f'Simulated EIT spectrum ($E = ${params["efield"]:.1f} V/cm)')
    ax.plot(freq, signal, linewidth=1.5)
    ax.fill_between(y1=signal, x=freq, y2=-2, color='C0', alpha=0.2)
    ax.scatter(x=freq, y=signal_noise, 
               marker='.', s=5,
               color='C3', alpha=0.5)
    # ax.plot(freq, df.best_fit, linewidth=1.5, color='C1')
    ef =  ref.interp(params['efield'])
    for label, amp, (fpos, _) in zip(ref.level_labels, params['rel_amp'], ef):
        ax.axvline(x=fpos, color='C3', linestyle='--')
    ax.set_xlabel('Detuning (MHz)')
    ax.set_ylabel('EIT Signal $S$ (%)')

# %%
