'''
Contains classes for electric field reconstruction
from Stark-split Rydberg EIT spectra 

Author: Mykhailo Vorobiov
'''
#%%
from typing import Callable, Dict
from numpy.typing import NDArray

import numpy as np
import matplotlib.pyplot as plt

import pandas as pd

from lmfit import minimize, Parameters, fit_report

from pinqued_tools.spectroscopy.spectrum import SpectralData, Axes0D
from pinqued_tools.spectroscopy.lineshapes import HoltsmarkLine
from pinqued_tools.spectroscopy.field_reference import FieldReference

class SignalSimulator():
    '''
    Class that based on the Rydberg levels Stark splitting 
    from generated by the `FieldReference` class simulates EIT spectra.
    '''
    def __init__(self, 
                 reference: FieldReference,
                 lineshape_func: Callable|None = None
                 ):
        self._reference = reference
        self._lineshape_func = lineshape_func

        if lineshape_func is None:
            print('No lineshape function provided, using Holtsmark lineshape by default.')
            self._hline_list = self._holtsmark_spectrum_prepare()
            print(len(self._hline_list))

    def _holtsmark_spectrum_prepare(self) -> list[HoltsmarkLine]:
        '''
        Simulate EIT signal for a given electric field using the Holtsmark lineshape.
        '''
        line_keys = self._reference.level_labels
        efield_reference = self._reference.efield
        stark_reference = self._reference.detunings[line_keys[0]]
        
        hline_list = []
        for key in line_keys:
             print(f'Preparing Holtsmark line for {key}...')
             stark_reference = self._reference.detunings[key]
             hline = HoltsmarkLine(efield_reference, stark_reference)
             # 1. Define your 4D parameter space
             freq_grid = np.linspace(-1200, 400, 300)  # <-- The frequency axis for the LUT
             efield_grid = np.linspace(0.0, 45.0, 30)
             E0_grid = np.linspace(0.01, 20.0, 20)
             width_grid = np.linspace(20.0, 50.0, 10)  # <-- The new dimension
             hline.build_lut(freq_grid, efield_grid, E0_grid, width_grid, base_model='2d')
             hline_list.append(hline)
             print(f'Finished preparing Holtsmark line for {key}.')

        print(f'Ready to simulate spectra with Holtsmark spectrum! Number of lines {len(hline_list)}')
        return hline_list

    def holtsmark_spectrum(self, 
                           freq: NDArray, 
                           params: Parameters
                           ) -> NDArray:
        '''
        Simulate EIT signal for a given electric field using the Holtsmark lineshape.
        '''
        efield = params['efield'].value
        scale_factor = params['amp'].value
        width = params['width'].value
        E0 = params['E0'].value
        r_amp = [params[f'rel_amp_{i}'].value for i in range(len(self._hline_list))]
        spectrum = np.zeros_like(freq)
        for hline, ai in zip(self._hline_list, r_amp):
            spectrum += hline(freq, efield, width, E0, ai)
        spectrum *= scale_factor
        return spectrum

    def holtsmark_spectrum_bg(self, 
                           freq: NDArray, 
                           params: Parameters
                           ) -> NDArray:
        '''
        Simulate EIT signal for a given electric field using the Holtsmark lineshape.
        '''
        signal = self.holtsmark_spectrum(freq, params)
        bg = self.bg_drifts(freq, params, poly_terms=2)
        spectrum = signal + bg
        return spectrum

    def signal(self, 
               freq: NDArray, 
               params: Parameters,
               **kwargs) -> NDArray[np.float64]:
        '''
        Simulate EIT signal for a given electric field
        '''
        scale_factor = params['amp'].value
        width_0 = params['width_0'].value
        gradE_dr = params['gradE_dr'].value
        efield = params['efield'].value

        ref = self._reference.interp(efield)

        spectrum = np.zeros_like(freq)
        r_amp = [params[f'rel_amp_{i}'].value for i in range(len(ref))]
        for (fpos, df_de), amp in zip(ref, r_amp):
            width = width_0  - df_de * gradE_dr
            spectrum += amp * self._lineshape_func(freq, fpos, width, **kwargs)
        spectrum *= scale_factor
        return spectrum
    
    def bg_drifts(self, 
                  freq: NDArray, 
                  params: Parameters,
                  poly_terms: int = 2,
                  **kwargs):
        coefs = [params[f'b{i}'].value for i in range(poly_terms) if params[f'b{i}'] is not None]
        poly = np.poly1d(coefs)
        if len(coefs) < poly_terms:
            return np.zeros_like(freq)
        return poly(freq)

    def signal_with_bg(self, 
                       freq: NDArray, 
                       params: Parameters,
                       poly_terms: int = 3,
                       **kwargs) -> NDArray[np.float64]:
        signal = self.signal(freq, params, **kwargs)
        bg = self.bg_drifts(freq, params, poly_terms=poly_terms)
        return signal + bg

    def signal_with_bg_shifted(self, 
                       freq: NDArray, 
                       params: Parameters,
                       poly_terms: int = 3,
                       **kwargs) -> NDArray[np.float64]:
        f_shifted = freq - params['f_shift'].value
        signal = self.signal(f_shifted, params, **kwargs)
        bg = self.bg_drifts(f_shifted, params, poly_terms=poly_terms)
        return signal + bg
    

class GPPoissonSignalSimulator1D(SignalSimulator):
    def __init__(self, 
                 reference: FieldReference,
                 px_size: float,
                 lineshape_func: Callable|None = None
                 ):
        super().__init__(reference, lineshape_func)
        self.px_size = px_size

    def holtsmark_spectrum(self, 
                           freq: NDArray, 
                           params: Parameters,
                           efield: float|NDArray|None = None,
                           grad_vec: float|NDArray|None = None
                           ) -> NDArray:
        '''
        Simulate EIT signal for a given electric field using the Holtsmark lineshape.
        Can accept spatial arrays for efield and grad_vec to vectorize the calculation.
        '''
        if efield is None:
            efield = params['efield'].value
        if grad_vec is None:
            grad_vec = params['grad_vec'].value
            
        scale_factor = params['amp'].value
        width = params['width'].value

        # THE LINK: Calculate Microscopic (Holtsmark) Scale E0
        # eps0 / e ≈ 5.5e7 (in mm^-3 units if z is mm)
        n_i_local = 5.5e7 * np.abs(grad_vec) 
        E0_local = 1.5e-7 * (n_i_local)**(2/3) # Example scaling constant

        # 1. Get Stark shift and sensitivity from reference
        # Note: spectral_sim.interp returns a list of (fpos, df_de) tuples
        # We take the first dominant line for this 1D model
        f0_dfdE_list_tuples = self._reference.interp(efield)
        dfdE = [np.asarray(tup[1]) for tup in f0_dfdE_list_tuples]

        r_amp = [params[f'rel_amp_{i}'].value for i in range(len(self._hline_list))]
        
        # Handle 1D (spatial) evaluation
        if np.ndim(efield) > 0:
            spectrum = np.zeros((len(efield), len(freq)))
        else:
            spectrum = np.zeros_like(freq)
            
        for i, (hline, ai) in enumerate(zip(self._hline_list, r_amp)):
            width_smear = np.sqrt(width**2 + (np.abs(dfdE[i] * grad_vec) * self.px_size)**2)
            # Explicitly trigger 'lut' model to pass arrays effectively
            spectrum += hline(freq, efield=efield, width=width + width_smear, E0=E0_local, amplitude=ai, model='lut')
            
        spectrum *= scale_factor
        return spectrum

#%%
if __name__=='__main__':
    pass

# %%
